GET http://localhost:8080/home

###
GET http://localhost:8080/notes/63346574d364ada37ccd5006

###

POST http://localhost:8080/notes/post
Content-Type: application/json

{
    "title": "3 October Log",
    "description": "just got back from jogja"
}

###

PATCH  http://localhost:8080/notes/edit/6339da379c7f387999f66959
Content-Type: application/json

{
    "title": "New True",
    "description": "awdaawd"
}



###

GET   http://localhost:8080/user


###

POST http://localhost:8080/signup
Content-Type: application/json

{
    "name": "Kylo Ren",
    "email": "kyloren@dankside.com",
    "password": "totest123"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "kyloren@dankside.com",
    "password": "totest123"
}

###
POST http://localhost:8080/postNotesById
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bG9yZW5AZGFua3NpZGUuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkUGVKaXNOYUVxOWw5enpscEtiZXZYT1hYV2FHTXFFMFBoTjRNYVJ0T3c5aWMzTzZ0QW5vdFMiLCJpYXQiOjE2NjUxNDUxMTQsImV4cCI6MTY2NTIzMTUxNH0.XOLwmSe0nljE64XTiSIEthzAMNc-c7T_9C_a09butvw
Content-Type: application/json

{
    "title": "Kylo Sith",
    "description": "The OG sith grandson"
}


###

GET http://localhost:8080/viewNotesByUserId
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bG9yZW5AZGFua3NpZGUuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkUGVKaXNOYUVxOWw5enpscEtiZXZYT1hYV2FHTXFFMFBoTjRNYVJ0T3c5aWMzTzZ0QW5vdFMiLCJpYXQiOjE2NjUxNDUxMTQsImV4cCI6MTY2NTIzMTUxNH0.XOLwmSe0nljE64XTiSIEthzAMNc-c7T_9C_a09butvw


//most testing are done using postman, so this file isn't always up to date
