GET http://localhost:8080/notes

###
GET http://localhost:8080/notes/63346574d364ada37ccd5006

###

POST http://localhost:8080/notes/post
Content-Type: application/json

{
    "title": "3 October Log",
    "description": "just got back from jogja"
}

###

PATCH  http://localhost:8080/notes/edit/6339da379c7f387999f66959
Content-Type: application/json

{
    "title": "New True",
    "description": "awdaawd"
}



###

GET   http://localhost:8080/person


###

POST http://localhost:8080/signup
Content-Type: application/json

{
    "name": "Harrison Ford",
    "email": "harrison@gmail.com",
    "password": "uniqlo"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "letdous@gmail.com",
    "password": "totest123"
}

###

POST http://localhost:8080/postNotesById
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnJpc29uQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGM4ZHc2Z2tpNUdZdlFTUkN1RnY5Ny5zbFQwdU44MDF5RzdtZm14Q1RTZ2FXWFFtRHoxR0syIiwiaWF0IjoxNjY0OTg5OTY2LCJleHAiOjE2NjQ5OTA4NjZ9.iOgdlG_CGjcs3xMoSq3Jx8yMdZFDy6jJv_6NAL48jc8
Content-Type: application/json

{
    "title": "The future of Ford vs Tesla",
    "description": "the future is still a long way to go, there's no need to act upon it"
}


###

GET http://localhost:8080/viewNotesById
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxldGRvdXNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka0pMVWhZbGxjcFdmTmRwZm5DV2RXLjBURm9ZQzhzbFhTcHhYMkd0dzhBclVGZmNPbmZPVXEiLCJpYXQiOjE2NjQ5OTE0MTcsImV4cCI6MTY2NDk5NTAxN30.wN0EZt_9Hl0vjWa-etVlGPE9S_GXmehgSbzHwRZTDvI


//most testing are done using postman, so this file isn't always up to date
