GET http://localhost:8080/notes

###
GET http://localhost:8080/notes/63346574d364ada37ccd5006

###

POST http://localhost:8080/notes/post
Content-Type: application/json

{
    "title": "3 October Log",
    "description": "just got back from jogja"
}

###

PATCH  http://localhost:8080/notes/edit/6339da379c7f387999f66959
Content-Type: application/json

{
    "title": "New True",
    "description": "awdaawd"
}



###

GET   http://localhost:8080/person


###

POST http://localhost:8080/person/post
Content-Type: application/json

{
    "name": "Harry Maguire the 2nd",
    "job": "Man Utd Captain the 2nd"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "letdous@gmail.com",
    "password": "totest123"
}

###
